service: payment-splitter
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  create-group:
    handler: src/modules/group/functions/create-group.handler
    events:
      - httpApi:
          path: /group
          method: post
  add-member-group:
    handler: src/modules/group/functions/add-member-group.handler
    events:
      - httpApi:
          path: /group/add-member
          method: post
  add-expense-group:
    handler: src/modules/group/functions/add-expense-group.handler
    events:
      - httpApi:
          path: /group/add-expense
          method: post
  view-balances:
    handler: src/modules/group/functions/view-balances-group.handler
    events:
      - httpApi:
          path: /group/{groupId}/balances
          method: get
  settle-debt-group:
    handler: src/modules/group/functions/settle-debt-group.handler
    events:
      - httpApi:
          path: /group/settle-debt
          method: post
plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

esbuild:
  bundle: true
  minify: false
  sourcemap: true
  target: "node20"
  exclude: 
    - "@aws-sdk/*"
  define: 
    "require.resolve": undefined
  platform: "node"
  concurrency: 10

resources:
  Resources:
    GroupTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: GROUP_TOPIC
    PaymentSplitter:
        Type: "AWS::DynamoDB::Table"
        Properties:
          BillingMode: "PAY_PER_REQUEST"
          TableName: "PaymentSplitter"
          AttributeDefinitions:
            - AttributeName: "pk"
              AttributeType: "S"
            - AttributeName: "sk"
              AttributeType: "S"
          KeySchema:
            - AttributeName: "pk"
              KeyType: "HASH"
            - AttributeName: "sk"
              KeyType: "RANGE"
        
