name: Deploy Serverless App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build Serverless App
        run: |
          npm run sls package -- --package dist

      - name: Deploy Serverless App - Production
        if: github.ref == 'refs/heads/main'
        run: npm run sls deploy --stage=production
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          AWS_ACCOUNT_REGION: ${{ secrets.AWS_ACCOUNT_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
